In [1]:
import pandas as pd
import numpy as np

In [4]:
billboard_100 = pd.read_csv("C:/Users/Admin/Documents/ironhack/BillboardFromLast20/billboardHot100_1999-2019_clean.csv")

In [5]:
billboard_100

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre,Writing.Credits,Features,top_genre,artists_original,main_artist,no_artists
0,['Lil Nas'],Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","['Country', 'Atlanta', 'Alternative Country', ...","Jozzy, Atticus ross, Trent reznor, Billy ray c...",Billy Ray Cyrus,Country,"Lil Nas,",Lil Nas,1
1,"['Shawn Mendes', ' Camila Cabello']",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",['Pop'],"Cashmere cat, Jack patterson, Charli xcx, Benn...",NaN,Pop,"Shawn Mendes, Camila Cabello",Shawn Mendes,2
2,['Billie Eilish'],Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","['Hip-Hop', 'Dark Pop', 'House', 'Trap', 'Meme...","Billie eilish, Finneas",NaN,Hip-Hop,Billie Eilish,Billie Eilish,1
3,['Khalid'],Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","['Synth-Pop', 'Pop']","Howard lawrence, Guy lawrence, Khalid",NaN,Synth-Pop,Khalid,Khalid,1
4,"['Ed Sheeran', ' Justin Bieber']",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","['Canada', 'UK', 'Dance', 'Dance-Pop', 'Pop']","Ed sheeran, Justin bieber, Shellback, Max mart...",NaN,Canada,"Ed Sheeran, Justin Bieber",Ed Sheeran,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97220,['Vitamin C'],Smile,95,NaN,NaN,1999-07-12,NaN,"['Jamaica', 'Pop']","Colleen fitzpatrick, Josh deutsch",Lady Saw,Jamaica,Vitamin C,Vitamin C,1
97221,['Collective Soul'],Heavy,96,73.0,20.0,1999-07-12,NaN,"['Hockey', 'Gaming', 'Soundtrack', 'Rock']",Collective soul,NaN,Hockey,Collective Soul,Collective Soul,1
97222,['Mary Chapin Carpenter'],Almost Home,97,NaN,NaN,1999-07-12,NaN,"['Country', 'Pop']","Annie roboff, Beth nielsen chapman, Mary chapi...",NaN,Country,Mary Chapin Carpenter,Mary Chapin Carpenter,1
97223,['Q'],Vivrant Thing,98,NaN,NaN,1999-07-12,NaN,['Rap'],"Q tip, J dilla, Barry white",NaN,Rap,Q,Q,1
97224,['The Offspring'],Why Don't You Get A Job?,100,74.0,15.0,1999-07-12,NaN,"['Ska', 'Punk Rock', 'Rock']",Dexter holland,NaN,Ska,The Offspring,The Offspring,1

In [6]:
artists = pd.read_csv("C:/Users/Admin/Documents/ironhack/BillboardFromLast20/artistDf.csv")

In [7]:
artists

,X,Artist,Followers,Genres,NumAlbums,YearFirstAlbum,Gender,Group.Solo
0,0,Ed Sheeran,52698756,"pop,uk pop",8,2011,M,Solo
1,1,Justin Bieber,30711450,"canadian pop,dance pop,pop,post-teen pop",10,2009,M,Solo
2,2,Jonas Brothers,3069527,"boy band,dance pop,pop,post-teen pop",10,2006,M,Group
3,3,Drake,41420478,"canadian hip hop,canadian pop,hip hop,pop rap,...",11,2010,M,Solo
4,4,Chris Brown,9676862,"dance pop,pop,pop rap,r&b,rap",6,2005,M,Solo
...,...,...,...,...,...,...,...,...
1030,1030,Dwight Yoakam,284597,"country,country rock,nashville sound,outlaw co...",25,1985,M,Solo
1031,1031,Jordan Knight,47229,NaN,4,1999,M,Solo
1032,1032,Lila McCann,42444,"contemporary country,country,country dawn",4,1997,F,Solo
1033,1033,Everlast,200550,rap rock,11,1990,M,Solo
1034,1034,Collective Soul,525701,"alternative metal,alternative rock,pop rock,po...",12,1994,M,Group

In [10]:
gender_artists = billboard_100.merge(right=artists, how="left", left_on="main_artist", right_on="Artist")

In [11]:
gender_artists.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre,Writing.Credits,Features,...,main_artist,no_artists,X,Artist,Followers,Genres,NumAlbums,YearFirstAlbum,Gender,Group.Solo
0,['Lil Nas'],Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","['Country', 'Atlanta', 'Alternative Country', ...","Jozzy, Atticus ross, Trent reznor, Billy ray c...",Billy Ray Cyrus,...,Lil Nas,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"['Shawn Mendes', ' Camila Cabello']",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",['Pop'],"Cashmere cat, Jack patterson, Charli xcx, Benn...",NaN,...,Shawn Mendes,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,['Billie Eilish'],Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","['Hip-Hop', 'Dark Pop', 'House', 'Trap', 'Meme...","Billie eilish, Finneas",NaN,...,Billie Eilish,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,['Khalid'],Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","['Synth-Pop', 'Pop']","Howard lawrence, Guy lawrence, Khalid",NaN,...,Khalid,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"['Ed Sheeran', ' Justin Bieber']",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","['Canada', 'UK', 'Dance', 'Dance-Pop', 'Pop']","Ed sheeran, Justin bieber, Shellback, Max mart...",NaN,...,Ed Sheeran,2,0.0,Ed Sheeran,52698756.0,"pop,uk pop",8.0,2011.0,M,Solo

In [12]:
gender_artists.to_csv("C:/Users/Admin/Documents/ironhack/BillboardFromLast20/artists_billboard_merge.csv", index=False)